# Ansible Playbook for Subutai Prime95 blueprint
---

- hosts: p95
  remote_user: root
  tasks: 

    - name: Upgrade debian                                                                                                                                                                     
      apt:                                                                                                                                                                                     
        update_cache: true                                                                                                                                                                     
        upgrade: "yes" 

    - name: Install required debs                                                                                                                                                              
      apt:                                                                                                                                                                                     
        name: 
          - libxml2
        state: present                                                                                                                                                                         

    - name: Create /root/prime
      file: 
        path: /root/prime
        state: directory

    - name: Fetch prime95
      unarchive: 
        src: http://www.mersenne.org/ftp_root/gimps/p95v298b6.linux64.tar.gz
        dest: /root/prime
        remote_src: yes
        creates: /root/prime/mprime

    - name: Create prime.txt
      template:
        src: files/prime.txt
        dest: /root/prime/prime.txt

    - name: Create local.txt
      template:
        src: files/local.txt
        dest: /root/prime/local.txt

    - name: Copy systemd unit
      template:
        src: files/mprime.service
        dest: /lib/systemd/system

    - name: Reload systemd
      systemd: daemon_reload=yes

    - name: Enable and start mprime
      systemd:
        name: mprime
        state: started
        enabled: true
        masked: no

# vim: ts=2 et nowrap autoindent
